sudo: required

services:
 - docker

language: bash

jobs:
  include:
  - stage: Build iobroker
    script:
    - DOCKER_ARCH=amd64 ./build/travis_build.sh
    env: DOCKER_ARCH=amd64
  - script:
    - DOCKER_ARCH=arm64 ./build/travis_build.sh
  - script:
    - DOCKER_ARCH=arm   ./build/travis_build.sh

  - stage: Build iobroker full
    script:
    - CONFIG_FILE="./build.all.config" DOCKER_ARCH=amd64 ./build/travis_build.sh
  - script:
    - CONFIG_FILE="./build.all.config" DOCKER_ARCH=arm64 ./build/travis_build.sh
  - script:
    - CONFIG_FILE="./build.all.config" DOCKER_ARCH=arm   ./build/travis_build.sh

  - stage: Manifest iobroker
    script:
    - ./build/travis_manifest.sh

  - stage: Manifest iobroker-full
    script:
    -  CONFIG_FILE="./build.all.config" ./build/travis_manifest.sh
