sudo: required

services:
 - docker

language: bash

jobs:
  include:
  - stage: Build iobroker
    script: ./build/cicd_build.sh
    env:
    - DOCKER_ARCH=amd64
  - script: ./build/cicd_build.sh
    env:
    - DOCKER_ARCH=arm64
  - script: ./build/cicd_build.sh
    env:
    - DOCKER_ARCH=arm

  - stage: Build iobroker full
    script: ./build/cicd_build.sh
    env:
    - DOCKER_ARCH=amd64
    - TAG_PREFIX=full-
    - CONFIG_FILE="./build.all.config"
  - script: ./build/cicd_build.sh
    env:
    - DOCKER_ARCH=arm64
    - TAG_PREFIX=full-
    - CONFIG_FILE="./build.all.config"
  - script: ./build/cicd_build.sh
    env:
    - DOCKER_ARCH=arm
    - TAG_PREFIX=full-
    - CONFIG_FILE="./build.all.config"

  - stage: Manifest
    script: ./build/cicd_manifest.sh

  - script: ./build/cicd_manifest.sh
    env:
      - TAG_PREFIX=full-
      - CONFIG_FILE="./build.all.config"
