sudo: required

services:
 - docker

language: bash

jobs:
  include:
  - stage: iobroker
    name: Build iobroker
    script:
    - ./build/travis_build.sh
    env:
      matrix:
      - DOCKER_ARCH=amd64
      - DOCKER_ARCH=arm64
      - DOCKER_ARCH=arm

  - stage: iobroker-full
    name: Build iobroker full
    script:
    - ./build/travis_build.sh
    env:
      - CONFIG_FILE="./build.all.config"
      - matrix:
        - DOCKER_ARCH=amd64
        - DOCKER_ARCH=arm64
        - DOCKER_ARCH=arm

  - stage: manifest
    name: Manifest iobroker
    script:
    - ./build/travis_manifest.sh
    env:

  - stage: Manifest-full
    name: Manifest iobroker-full
    script:
    -  ./build/travis_manifest.sh
    env:
    - CONFIG_FILE="./build.all.config"
