sudo: required

services:
 - docker

language: bash

jobs:
  include:
  - stage: iobroker
    name: Build iobroker
    script:
    - DOCKER_ARCH=amd64 ./build/travis_build.sh
    - DOCKER_ARCH=arm64 ./build/travis_build.sh
    - DOCKER_ARCH=arm   ./build/travis_build.sh

  - stage: iobroker-full
    name: Build iobroker full
    script:
    - DOCKER_ARCH=amd64 ./build/travis_build.sh
    - DOCKER_ARCH=arm64 ./build/travis_build.sh
    - DOCKER_ARCH=arm   ./build/travis_build.sh
    env:
    - CONFIG_FILE="./build.all.config"

  - stage: manifest
    name: Manifest iobroker
    script:
    - ./build/travis_manifest.sh
    env:

  - stage: Manifest-full
    name: Manifest iobroker-full
    script:
    -  ./build/travis_manifest.sh
    env:
    - CONFIG_FILE="./build.all.config"
